before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./go.sh completions

builds:
  - id: lico-build
    env:
      - CGO_ENABLED=0
    main: ./main.go
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w 
      - -X github.com/Hayao0819/lico/vars.version={{.Version}} 
      - -X github.com/Hayao0819/lico/vars.commit={{.Commit}} 
      - -X github.com/Hayao0819/lico/vars.date={{.Date}}
      #- -X github.com/Hayao0819/lico/vars.builtBy=goreleaser

release:
  mode: keep-existing
  prerelease: auto

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
    files:
      - LICENSE.txt
      - SUSHI.md
      - README.md
      - src: 'out/completions/lico.*'
        dst: "shell"
        strip_parent: true
    rlcp: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-{{ .ShortCommit }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    name: lico
    tap:
      owner: Hayao0819
      name: homebrew-tap
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    license: "MIT"
    url_template: "https://github.com/Hayao0819/lico/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: hayao
      email: hayao@fascode.net
    homepage: "https://github.com/Hayao0819/lico"
    description: "CLI tool for managing dotfiles"
    test: |
      system "#{bin}/lico help"
    install: |
      bin.install "lico"
      bash_completion.install "shell/lico.bash" => "lico"
      zsh_completion.install "shell/lico.zsh" => "lico"
      fish_completion.install "shell/lico.fish"
    dependencies:
      - name: git

nfpms:
  - id: lico-packaging
    package_name: lico
    builds:
      - "lico-build"
    vendor: Hayao0819
    homepage: "https://github.com/Hayao0819/lico"
    maintainer: Hayao0819 <hayao@fascode.net>
    description: "CLI tool for managing dotfiles"
    license: MIT
    formats:
      - deb
      - rpm
    version_metadata: git
    


# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
