name: test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        run: go test -v ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

